# daily-git-check.ps1 - Daily Git Health Report
# Output: E:\ai产出文件\log\YYYY-MM-DD.md

$ErrorActionPreference = 'Continue'
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

$gitRoot = (git rev-parse --show-toplevel 2>$null)
if (-not $gitRoot) {
    Write-Host '[ERROR] Not a git repository'
    exit 1
}

$reportDir = 'E:\ai产出文件\log'
if (-not (Test-Path $reportDir)) {
    New-Item -ItemType Directory -Path $reportDir -Force | Out-Null
}

$today = Get-Date -Format 'yyyy-MM-dd'
$yesterday = (Get-Date).AddDays(-1).ToString('yyyy-MM-dd')
$reportFile = Join-Path $reportDir "$today.md"

$yesterdayCommits = git log --after="$yesterday 00:00" --before="$today 00:00" --oneline 2>$null
$yesterdayCommitCount = 0
if ($yesterdayCommits) { $yesterdayCommitCount = ($yesterdayCommits | Measure-Object).Count }

$recentCommits = git log --oneline -5 2>$null
if (-not $recentCommits) { $recentCommits = '(none)' }

$statusOutput = git status --porcelain 2>$null
$modifiedCount = 0; $untrackedCount = 0; $deletedCount = 0; $totalUncommitted = 0
if ($statusOutput) {
    $modifiedCount = ($statusOutput | Where-Object { $_ -match '^ ?M' } | Measure-Object).Count
    $untrackedCount = ($statusOutput | Where-Object { $_ -match '^\?\?' } | Measure-Object).Count
    $deletedCount = ($statusOutput | Where-Object { $_ -match '^ ?D' } | Measure-Object).Count
    $totalUncommitted = ($statusOutput | Measure-Object).Count
}

$localHash = git rev-parse HEAD 2>$null
$remoteHash = git rev-parse origin/main 2>$null
$commitsAhead = 0; $commitsBehind = 0; $remoteStatus = 'N/A'
if ($localHash -and $remoteHash) {
    $commitsAhead = [int](git rev-list "$remoteHash..$localHash" --count 2>$null)
    $commitsBehind = [int](git rev-list "$localHash..$remoteHash" --count 2>$null)
    if ($commitsAhead -eq 0 -and $commitsBehind -eq 0) {
        $remoteStatus = '[OK] Synced'
    } elseif ($commitsAhead -gt 0) {
        $remoteStatus = "[WARN] Local ahead by $commitsAhead commits"
    } else {
        $remoteStatus = "[WARN] Remote ahead by $commitsBehind commits"
    }
}

$giteeHash = git rev-parse gitee/main 2>$null
$giteeStatus = 'N/A'
if ($giteeHash) {
    $giteeAhead = [int](git rev-list "$giteeHash..$localHash" --count 2>$null)
    $giteeBehind = [int](git rev-list "$localHash..$giteeHash" --count 2>$null)
    if ($giteeAhead -eq 0 -and $giteeBehind -eq 0) {
        $giteeStatus = '[OK] Synced'
    } elseif ($giteeAhead -gt 0) {
        $giteeStatus = "[WARN] Local ahead by $giteeAhead"
    } else {
        $giteeStatus = "[WARN] Gitee ahead by $giteeBehind"
    }
}

$logFile = Join-Path $gitRoot 'git-auto-commit.log'
$lastAutoCommit = 'N/A'
if (Test-Path $logFile) {
    $logContent = Get-Content $logFile -Tail 10 -Encoding UTF8
    $lastSuccessLine = $logContent | Where-Object { $_ -match 'Commit successful|Pushed|OK' } | Select-Object -Last 1
    if ($lastSuccessLine) { $lastAutoCommit = $lastSuccessLine.Trim() }
}

$isHealthy = $true
$issues = @()
if ($yesterdayCommitCount -eq 0) { $issues += 'No commits yesterday' }
if ($totalUncommitted -gt 50) { $issues += "$totalUncommitted uncommitted changes (>50)"; $isHealthy = $false }
if ($commitsAhead -gt 5) { $issues += "$commitsAhead unpushed commits"; $isHealthy = $false }
if ($deletedCount -gt 0) { $issues += "$deletedCount deleted files" }

$statusLabel = if ($isHealthy) { 'HEALTHY' } else { 'NEEDS ATTENTION' }
$issuesText = if ($issues.Count -eq 0) { 'No issues detected.' } else { ($issues | ForEach-Object { "- $_" }) -join "`n" }

$report = @"
# Git Daily Health Report - $today

## Status: $statusLabel

## Yesterday ($yesterday): $yesterdayCommitCount commits

## Working Tree
- Modified: $modifiedCount
- Untracked: $untrackedCount
- Deleted: $deletedCount
- Total: $totalUncommitted

## Remote Sync
- GitHub: $remoteStatus
- Gitee: $giteeStatus

## Recent Commits
$recentCommits

## Last Auto-Commit
$lastAutoCommit

## Issues
$issuesText

---
*Auto-generated by daily-git-check.ps1*
"@

$utf8Bom = New-Object System.Text.UTF8Encoding $true
[System.IO.File]::WriteAllText($reportFile, $report, $utf8Bom)

Write-Host '========================================='
Write-Host "  Git Daily Report - $today"
Write-Host '========================================='
Write-Host "Status: $statusLabel"
Write-Host "Yesterday commits: $yesterdayCommitCount"
Write-Host "Uncommitted: $totalUncommitted"
Write-Host "GitHub: $remoteStatus"
Write-Host "Gitee: $giteeStatus"
Write-Host "Report: $reportFile"
Write-Host '========================================='
